name: Test CICD

on: [push]

jobs:
  selenium-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Selenium Tests
        run: |
          python main.py

      - name: Show All Test Logs in Console
        run: cat test_*.log || true  # 允许 cat 失败，避免影响流程

      - name: Upload Test Logs
        uses: actions/upload-artifact@v4
        with:
          name: selenium-logs
          path: test_*.log
